<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Vasant" failures="1" tests="3" name="Test(failed)" time="0.143" errors="0" timestamp="2025-04-27T12:11:08 IST">
  <testcase classname="com.testng.FailedTestExecution" name="test5" time="0.027">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.testng.FailedTestExecution.test5(FailedTestExecution.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase classname="com.testng.FailedTestExecution" name="test4" time="0.005"/>
  <testcase classname="com.testng.FailedTestExecution" name="test2" time="0.008"/>
  <testcase classname="com.testng.FailedTestExecution" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="com.testng.FailedTestExecution" name="test6" time="0.0">
    <ignored/>
  </testcase> <!-- test6 -->
  <testcase classname="com.testng.FailedTestExecution" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test(failed) -->
